---
# Service to expose web frontend

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data:
  config.json: |
    {
      "tls_cert_file": "/vault/secrets/tls-cert",
      "tls_key_file": "/vault/secrets/tls-key",
      "db_connection": "host=postgres port=5432 user=postgres password=password dbname=products sslmode=disable",
      "bind_address": ":9090"
    }

---
# Service account to allow pod access to Vault via K8s auth

apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
automountServiceAccountToken: true

---
# Web frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-tls-cert: "pki/issue/shipyard.run"
        vault.hashicorp.com/agent-inject-template-tls-cert: |
          {{ with secret "pki/issue/shipyard.run" "common_name=web.ingress.shipyard.run" -}}
            {{ .Data.certificate }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-tls-key: "pki/issue/shipyard.run"
        vault.hashicorp.com/agent-inject-template-tls-key: |
          {{ with secret "pki/issue/shipyard.run" "common_name=web.ingress.shipyard.run" -}}
            {{ .Data.private_key }}
          {{- end }}
        vault.hashicorp.com/role: "web"
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: nicholasjackson/vault-demo-app:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "CONFIG_FILE"
              value: "/etc/config/config.json"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: config
